{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "[Server] gRPC Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_grpc_SayHello_success{service=\"grpc-server-service\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Server] gRPC Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_grpc_SayHello_failure{service=\"grpc-server-service\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Client] gRPC Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_grpc_SayHello_success{service=\"grpc-client-service\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Client] gRPC Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_grpc_SayHello_failure{service=\"grpc-client-service\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}