apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: apps:latest
          imagePullPolicy: IfNotPresent
          command: ["/app", "server"]
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  selector:
    app: grpc-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: apps:latest
          imagePullPolicy: IfNotPresent
          command: ["/app", "client"]
          args: ["--address", "grpc-server-service:9090", "--qps", "1", "--duration", "30m"]
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-client-service
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: grpc-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
