apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: apps:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
          command: ["/app", "server"]
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: envoy-container
          image: envoyproxy/envoy:v1.29.1
          ports:
            - containerPort: 9090
            - containerPort: 8080
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
          command: ["/usr/local/bin/envoy"]
          args: ["--config-path", "/etc/envoy/envoy.yaml", "--log-level", "debug"]
      volumes:
        - name: envoy-config
          configMap:
            name: server-envoy-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    prometheus.io/path: '/stats/prometheus'
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: grpc-server
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: grpc2
      protocol: TCP
      port: 9091
      targetPort: 9091
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: apps:latest
          imagePullPolicy: IfNotPresent
          command: ["/app", "client"]
          args: ["--address", "localhost:9090", "--qps", "1", "--duration", "30m"]
          env:
            - name: "PROXY_URL"
              value: "127.0.0.1:9091"
            - name: TARGET_URL
              value: "grpc-server-service.default:9090"
            - name: GRPC_GO_LOG_SEVERITY_LEVEL
              value: info
        - name: envoy-container
          image: envoyproxy/envoy:v1.29.1
          ports:
            - containerPort: 9090
            - containerPort: 8080
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
          command: ["/usr/local/bin/envoy"]
          args: ["--config-path", "/etc/envoy/envoy.yaml", "--log-level", "debug"]
      volumes:
        - name: envoy-config
          configMap:
            name: client-envoy-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-client-service
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    prometheus.io/path: '/stats/prometheus'
spec:
  selector:
    app: grpc-client
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: server-envoy-configmap
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 9090
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                      grpc: {}
                    route:
                      cluster: server
              http_filters:
                - name: envoy.filters.http.grpc_stats
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
                    stats_for_all_methods: true
                    enable_upstream_stats: true
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: server
          connect_timeout: 0.25s
          type: strict_dns
          lb_policy: round_robin
          dns_lookup_family: V4_ONLY
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options: {}
          load_assignment:
            cluster_name: server
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 9091


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: client-envoy-configmap
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 9090
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: dynamic_forward_proxy_cluster
                      retry_policy:
                        #retry_on: "5xx"
                        retry_on: "5xx,cancelled,deadline-exceeded,resource-exhausted,unavailable"
                        num_retries: 5
                        per_try_timeout: 2s
                        retry_host_predicate:
                          - name: envoy.retry_host_predicates.previous_hosts
                            typed_config:
                              "@type": type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate
              http_filters:
              - name: envoy.filters.http.dynamic_forward_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                  dns_cache_config:
                    name: dynamic_forward_proxy_cache_config
                    dns_refresh_rate: 1s
                    host_ttl: 1s
                    dns_lookup_family: V4_ONLY
                    typed_dns_resolver_config:
                      name: envoy.network.dns_resolver.cares
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                        # Enable resolvers as a fallback, forcing DNS resolution through the pod resolv.conf (kube-proxy)
                        use_resolvers_as_fallback: true
                        dns_resolver_options:
                          # Enable default search domains so that '*.svc.cluster.local' does not need to be specified
                          no_default_search_domain: false
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
      - name: dynamic_forward_proxy_cluster
        lb_policy: CLUSTER_PROVIDED
        # Must include http2_protocol_options to allow for gRPC trailers to be supported
        http2_protocol_options: {}
        dns_refresh_rate: 1s
        health_checks:
        - timeout: 5s
          interval: 5s
          unhealthy_threshold: 1
          healthy_threshold: 1
          grpc_health_check: {}
        cluster_type:
          name: envoy.clusters.dynamic_forward_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
            sub_clusters_config:
              lb_policy: ROUND_ROBIN
